[camera]
device = 0
width = 640
height = 480
fps = 30

[video]
width = 640
height = 480
fps = 15
jpeg_quality = 50
port = 5600

[line]
offset_normalized = false
intersection_threshold = 0.8

[aruco]
dictionary = "DICT_4X4_50"
