[camera]
device = 0
width = 640
height = 480
fps = 30

[video]
width = 640
height = 480
fps = 15
jpeg_quality = 50
port = 5600

[line]
offset_normalized = false
intersection_threshold = 0.8

[aruco]
dictionary = "DICT_4X4_50"
marker_size_mm = 80.0
min_marker_perimeter_rate = 0.03
max_marker_perimeter_rate = 4.0
adaptive_thresh_win_size_min = 3
adaptive_thresh_win_size_max = 23
adaptive_thresh_win_size_step = 10
